### PR TITLE
Upgrade the zeromq lib

### PR DESCRIPTION
**Pull request by guenhter**
Simple attempt just to upgrade the version of some libs.
The tests still passes. Only thing is that the feature "vendored" is now removed (which is somehow a braking change).

### CODE REVIEW

**Comment by guenhter** [comment]
Fixes https://github.com/rdelfin/async-zmq/issues/21

**Comment by rdelfin** [comment]
Thanks for doing this @guenhter! I'll review and get this in

**Comment by rdelfin** [comment]
Thanks for doing this @guenhter! I'll review and get this in

**Comment by rdelfin** [comment]
Interesting... The vendored version was quite useful. I'll make this a major version bump in that case

**Comment by guenhter** [comment]
What was the purpose of the "vendored" version?

**Comment by rdelfin** [comment]
Vendoring ensured that the version of ZMQ would be built and included in the resulting artifact. As it stands without vendoring, you need to separately install ZMQ as a system dependency always, and that gets dynamically linked against your program. Having the option is nice, but this is probably gonna give you more consistent results if you work with binaries written in other languages

**Review by rdelfin — APPROVED** [review]

**Comment by rdelfin** [comment]
I'm not sure why the test isn't running, so I'll merge as-is and test in post-submit

**Comment by guenhter** [comment]
I'll ask in the zmq lib, why the vendored feature was removed because it sounds very useful though.

**Pull request merged**
